/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedNumbersRouteImport } from './routes/_authenticated/numbers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedAssistantSidRouteImport } from './routes/_authenticated/assistant.$sid'
import { Route as AuthenticatedInboxIndexRouteImport } from './routes/_authenticated/inbox/index'
import { Route as AuthenticatedInboxIdRouteImport } from './routes/_authenticated/inbox/$id'
import { Route as ApiPublicElevenlabsPostCallRouteImport } from './routes/api/public/elevenlabs/post-call'
import { Route as ApiPublicTwilioAppVoiceRouteImport } from './routes/api/public/twilio/app-voice'
import { Route as ApiPublicTwilioSmsRouteImport } from './routes/api/public/twilio/sms'
import { Route as ApiPublicTwilioStatusRouteImport } from './routes/api/public/twilio/status'
import { Route as ApiPublicTwilioVoiceRouteImport } from './routes/api/public/twilio/voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNumbersRoute = AuthenticatedNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantSidRoute =
  AuthenticatedAssistantSidRouteImport.update({
    id: '/assistant/$sid',
    path: '/assistant/$sid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboxIndexRoute = AuthenticatedInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxIdRoute = AuthenticatedInboxIdRouteImport.update({
  id: '/inbox/$id',
  path: '/inbox/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicElevenlabsPostCallRoute =
  ApiPublicElevenlabsPostCallRouteImport.update({
    id: '/api/public/elevenlabs/post-call',
    path: '/api/public/elevenlabs/post-call',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTwilioAppVoiceRoute = ApiPublicTwilioAppVoiceRouteImport.update({
  id: '/api/public/twilio/app-voice',
  path: '/api/public/twilio/app-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioSmsRoute = ApiPublicTwilioSmsRouteImport.update({
  id: '/api/public/twilio/sms',
  path: '/api/public/twilio/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioStatusRoute = ApiPublicTwilioStatusRouteImport.update({
  id: '/api/public/twilio/status',
  path: '/api/public/twilio/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioVoiceRoute = ApiPublicTwilioVoiceRouteImport.update({
  id: '/api/public/twilio/voice',
  path: '/api/public/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/numbers': typeof AuthenticatedNumbersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/assistant/$sid': typeof AuthenticatedAssistantSidRoute
  '/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/inbox/': typeof AuthenticatedInboxIndexRoute
  '/api/public/elevenlabs/post-call': typeof ApiPublicElevenlabsPostCallRoute
  '/api/public/twilio/app-voice': typeof ApiPublicTwilioAppVoiceRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/console': typeof AuthenticatedConsoleRoute
  '/numbers': typeof AuthenticatedNumbersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/assistant/$sid': typeof AuthenticatedAssistantSidRoute
  '/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/inbox': typeof AuthenticatedInboxIndexRoute
  '/api/public/elevenlabs/post-call': typeof ApiPublicElevenlabsPostCallRoute
  '/api/public/twilio/app-voice': typeof ApiPublicTwilioAppVoiceRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRoute
  '/_authenticated/numbers': typeof AuthenticatedNumbersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/assistant/$sid': typeof AuthenticatedAssistantSidRoute
  '/_authenticated/inbox/$id': typeof AuthenticatedInboxIdRoute
  '/_authenticated/inbox/': typeof AuthenticatedInboxIndexRoute
  '/api/public/elevenlabs/post-call': typeof ApiPublicElevenlabsPostCallRoute
  '/api/public/twilio/app-voice': typeof ApiPublicTwilioAppVoiceRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calls'
    | '/console'
    | '/numbers'
    | '/settings'
    | '/tools'
    | '/assistant/$sid'
    | '/inbox/$id'
    | '/inbox/'
    | '/api/public/elevenlabs/post-call'
    | '/api/public/twilio/app-voice'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calls'
    | '/console'
    | '/numbers'
    | '/settings'
    | '/tools'
    | '/assistant/$sid'
    | '/inbox/$id'
    | '/inbox'
    | '/api/public/elevenlabs/post-call'
    | '/api/public/twilio/app-voice'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/calls'
    | '/_authenticated/console'
    | '/_authenticated/numbers'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
    | '/_authenticated/assistant/$sid'
    | '/_authenticated/inbox/$id'
    | '/_authenticated/inbox/'
    | '/api/public/elevenlabs/post-call'
    | '/api/public/twilio/app-voice'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/status'
    | '/api/public/twilio/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicElevenlabsPostCallRoute: typeof ApiPublicElevenlabsPostCallRoute
  ApiPublicTwilioAppVoiceRoute: typeof ApiPublicTwilioAppVoiceRoute
  ApiPublicTwilioSmsRoute: typeof ApiPublicTwilioSmsRoute
  ApiPublicTwilioStatusRoute: typeof ApiPublicTwilioStatusRoute
  ApiPublicTwilioVoiceRoute: typeof ApiPublicTwilioVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/numbers': {
      id: '/_authenticated/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof AuthenticatedNumbersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant/$sid': {
      id: '/_authenticated/assistant/$sid'
      path: '/assistant/$sid'
      fullPath: '/assistant/$sid'
      preLoaderRoute: typeof AuthenticatedAssistantSidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox/': {
      id: '/_authenticated/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthenticatedInboxIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox/$id': {
      id: '/_authenticated/inbox/$id'
      path: '/inbox/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof AuthenticatedInboxIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/elevenlabs/post-call': {
      id: '/api/public/elevenlabs/post-call'
      path: '/api/public/elevenlabs/post-call'
      fullPath: '/api/public/elevenlabs/post-call'
      preLoaderRoute: typeof ApiPublicElevenlabsPostCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/app-voice': {
      id: '/api/public/twilio/app-voice'
      path: '/api/public/twilio/app-voice'
      fullPath: '/api/public/twilio/app-voice'
      preLoaderRoute: typeof ApiPublicTwilioAppVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/sms': {
      id: '/api/public/twilio/sms'
      path: '/api/public/twilio/sms'
      fullPath: '/api/public/twilio/sms'
      preLoaderRoute: typeof ApiPublicTwilioSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/status': {
      id: '/api/public/twilio/status'
      path: '/api/public/twilio/status'
      fullPath: '/api/public/twilio/status'
      preLoaderRoute: typeof ApiPublicTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/voice': {
      id: '/api/public/twilio/voice'
      path: '/api/public/twilio/voice'
      fullPath: '/api/public/twilio/voice'
      preLoaderRoute: typeof ApiPublicTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRoute
  AuthenticatedNumbersRoute: typeof AuthenticatedNumbersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedAssistantSidRoute: typeof AuthenticatedAssistantSidRoute
  AuthenticatedInboxIdRoute: typeof AuthenticatedInboxIdRoute
  AuthenticatedInboxIndexRoute: typeof AuthenticatedInboxIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedConsoleRoute: AuthenticatedConsoleRoute,
  AuthenticatedNumbersRoute: AuthenticatedNumbersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedAssistantSidRoute: AuthenticatedAssistantSidRoute,
  AuthenticatedInboxIdRoute: AuthenticatedInboxIdRoute,
  AuthenticatedInboxIndexRoute: AuthenticatedInboxIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicElevenlabsPostCallRoute: ApiPublicElevenlabsPostCallRoute,
  ApiPublicTwilioAppVoiceRoute: ApiPublicTwilioAppVoiceRoute,
  ApiPublicTwilioSmsRoute: ApiPublicTwilioSmsRoute,
  ApiPublicTwilioStatusRoute: ApiPublicTwilioStatusRoute,
  ApiPublicTwilioVoiceRoute: ApiPublicTwilioVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
